a.out: Pointers.o prog1.o prog2.o
	g++ -g Pointers.o prog1.o prog2.o

Pionters.o: Pointers.cpp
	g++ -c -g Pionters.cpp

prog1.o: prog1.cpp
	g++ -c -g prog1.cpp

prog2.o: prog2.cpp
	g++ -c -g prog2.cpp
